language: node_js
before_script:
  - sh -e /etc/init.d/xvfb start
  - npm install -g jpm
env:
  - DISPLAY=':99.0'
script: 
  - export JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/../firefox/firefox
  - jpm test
sudo: false
